"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createAuthClient } from "../../utils/supabase/auth-server";

export type ResortState = { error?: string };

export async function saveResort(id: string | null, _state: ResortState, form: FormData): Promise<ResortState> {
  const client = await createAuthClient();
  const { data: { user }, error: authError } = await client.auth.getUser();
  if (authError || !user) return { error: "Prisijunkite, kad galėtumėte išsaugoti kurortą." };
  const { data: claimsData, error: claimsError } = await client.auth.getClaims();
  const ownerMatchesToken = !claimsError && claimsData?.claims.sub === user.id;
  if (!ownerMatchesToken) return { error: "Sesijos patikra nepavyko. Prisijunkite iš naujo tame pačiame naršyklės adrese." };
  const name = String(form.get("name") ?? "").trim();
  const country = String(form.get("country") ?? "").trim();
  const description = String(form.get("description") ?? "").trim();
  const category = String(form.get("category") ?? "").trim();
  const kilometers = ["blue_km", "red_km", "black_km"].map((field) => {
    const raw = String(form.get(field) ?? "").trim();
    return raw === "" ? NaN : Number(raw.replace(",", "."));
  });
  if (!name || name.length > 150 || !country || country.length > 100 || !description || description.length > 2000 || !["Šeimoms", "Pradedantiesiems", "Pažengusiems", "Universalus"].includes(category) || kilometers.some((value) => !Number.isFinite(value) || value < 0 || value > 10000)) {
    return { error: "Užpildykite visus laukus. Trasų kilometrai turi būti nuo 0 iki 10 000." };
  }
  const [blue_km, red_km, black_km] = kilometers;
  // total_km is generated by PostgreSQL; never send it in INSERT or UPDATE.
  const values = { name, country, description, category, blue_km, red_km, black_km };
  const query = id === null
    ? client.from("resorts").insert({ ...values, user_id: user.id })
    : client.from("resorts").update(values).eq("id", id).eq("user_id", user.id);
  const { data, error } = await query.select("id").maybeSingle();
  if (error) console.error("Resort save failed", JSON.stringify({ operation: id === null ? "INSERT" : "UPDATE", code: error.code, message: error.message, ownerMatchesToken }));
  if (error || !data) return { error: "Nepavyko išsaugoti. Įrašas gali būti pašalintas arba nepriklausyti jums. Bandykite dar kartą." };
  revalidatePath("/");
  redirect("/");
}

export async function deleteResort(id: string): Promise<ResortState> {
  const client = await createAuthClient();
  const { data: { user }, error: authError } = await client.auth.getUser();
  if (authError || !user) return { error: "Prisijunkite, kad galėtumėte ištrinti kurortą." };
  const { data, error } = await client.from("resorts").delete().eq("id", id).eq("user_id", user.id).select("id").maybeSingle();
  if (error || !data) return { error: "Nepavyko ištrinti. Įrašas gali būti pašalintas arba nepriklausyti jums." };
  revalidatePath("/");
  return {};
}
